/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GraphColoringViewPanel.java
 *
 * Created on Dec 25, 2010, 9:26:59 PM
 */
package hgb.csp.problems.graphcoloring;

import hgb.csp.domain.Constraint;
import hgb.csp.domain.Variable;
import hgb.csp.search.mvc.SearchEvent;
import hgb.csp.mvc.Handles;
import hgb.csp.view.ProblemVisualization;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridLayout;
import javax.swing.SwingUtilities;
import org.jgraph.JGraph;
import org.jgraph.graph.AttributeMap;
import org.jgraph.graph.DefaultGraphCell;
import org.jgraph.graph.GraphConstants;
import org.jgrapht.ListenableGraph;
import org.jgrapht.ext.JGraphModelAdapter;

/**
 *
 * @author Alexander
 */
public class GraphColoringViewPanel extends javax.swing.JPanel implements ProblemVisualization {

    private static final Color DEFAULT_BG_COLOR = Color.decode("#FAFBFF");
    private static final Dimension DEFAULT_SIZE = new Dimension(600, 400);
    private GraphLayouter layouter;

    JGraph jgraph;
    ListenableGraph<Variable, Constraint> constraintGraph;
    JGraphModelAdapter<Variable, Constraint> graphModelApapter;

    /** Creates new form GraphColoringViewPanel */
    public GraphColoringViewPanel() {
        initComponents();
        layouter = new GraphLayouter();
    }

    public void bind(ListenableGraph<Variable, Constraint> csp) {
        constraintGraph = csp;
        graphModelApapter = new JGraphModelAdapter<Variable, Constraint>(csp);
        graphContainer.removeAll();
        jgraph = new JGraph(graphModelApapter);
        adjustDisplaySettings(jgraph);
        graphContainer.add(jgraph);
        graphContainer.setLayout(new GridLayout(1, 1));

        layouter.layout(csp, jgraph, graphModelApapter);
        this.updateUI();
    }

    private void adjustDisplaySettings(JGraph jg) {
        jg.setPreferredSize(DEFAULT_SIZE);
        Color c = DEFAULT_BG_COLOR;
        jg.setBackground(c);
    }

    @Handles(type=SearchEvent.ASSIGNMENT_OCCURED)
    public synchronized void assignmentHappened(SearchEvent se) {
        // redraw call necessary
        SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                for (Variable v : constraintGraph.vertexSet()) {
                    colorVertex(v, getColorFor(v));
                }
            }
        });
        
    }

    private void colorVertex(Object vertex, Color c) {
        DefaultGraphCell cell = graphModelApapter.getVertexCell(vertex);
        AttributeMap attr = cell.getAttributes();
        GraphConstants.setBackground(attr, c);
        AttributeMap cellAttr = new AttributeMap();
        cellAttr.put(cell, attr);
        graphModelApapter.edit(cellAttr, null, null, null);
    }

    private Color getColorFor(Variable v) {

        if (v.getAssignedValue() == null) {
            return Color.gray;
        }

        // this instance can safely assume that values are integers
        int ci = (Integer)v.getAssignedValue();
        switch (ci) {
            case 1:
                return Color.red;
            case 2:
                return Color.blue;
            case 3:
                return Color.green;

        }
        return Color.gray;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        graphContainer = new javax.swing.JPanel();

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel1.setText("Graph coloring problem visualization");

        graphContainer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        graphContainer.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);

        javax.swing.GroupLayout graphContainerLayout = new javax.swing.GroupLayout(graphContainer);
        graphContainer.setLayout(graphContainerLayout);
        graphContainerLayout.setHorizontalGroup(
            graphContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 705, Short.MAX_VALUE)
        );
        graphContainerLayout.setVerticalGroup(
            graphContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 411, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(graphContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(415, 415, 415))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(graphContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel graphContainer;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
