/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * StatisticsPanel.java
 *
 * Created on Dec 25, 2010, 9:02:45 PM
 */

package hgb.csp.view;

import hgb.csp.search.mvc.SearchEvent;
import hgb.csp.mvc.Handles;
import hgb.csp.statistics.DataEvent;
import hgb.csp.statistics.RunData;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.SwingUtilities;

/**
 *
 * @author Alexander
 */
public class StatisticsPanel extends javax.swing.JPanel {
  
    private final DateFormat df = new SimpleDateFormat("mm:ss");

    /** Creates new form StatisticsPanel */
    public StatisticsPanel() {
        initComponents();
    }

    @Handles(type=DataEvent.DATA_CHANGED)
    public void update(DataEvent de) {
        final RunData runData = de.getCurrentRun();
        SwingUtilities.invokeLater(new Runnable() {

            public void run() {
                refreshText(runData);
            }
        });
    }

    protected void refreshText(RunData data) {
        consistencyLabel.setText(data.getCounterFor(RunData.CONSISTENCY_CHECKS).toString());
        assignmentsLabel.setText(data.getCounterFor(RunData.ASSIGNMENTS).toString());
        recursiveLabel.setText(data.getCounterFor(RunData.ITERATIONS_COUNT).toString());
        long elapsed = data.getElapsedTime();
        elapsedLabel.setText(df.format(new Date(elapsed)));
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      statisticsImage = new javax.swing.ImageIcon();
      jTabbedPane1 = new javax.swing.JTabbedPane();
      currentRun = new javax.swing.JPanel();
      elapsedLabel = new javax.swing.JLabel();
      consistencyLabel = new javax.swing.JLabel();
      recursiveLabel = new javax.swing.JLabel();
      assignmentsLabel = new javax.swing.JLabel();
      jLabel5 = new javax.swing.JLabel();
      jLabel6 = new javax.swing.JLabel();
      jLabel4 = new javax.swing.JLabel();
      jLabel3 = new javax.swing.JLabel();
      jLabel1 = new javax.swing.JLabel();
      jLabel2 = new javax.swing.JLabel();
      jPanel2 = new javax.swing.JPanel();

      elapsedLabel.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
      elapsedLabel.setText("0");

      consistencyLabel.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
      consistencyLabel.setText("0");

      recursiveLabel.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
      recursiveLabel.setText("0");

      assignmentsLabel.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
      assignmentsLabel.setText("0");

      jLabel5.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
      jLabel5.setText("Elapsed time");

      jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hgb/csp/resources/chart.png"))); // NOI18N

      jLabel4.setFont(new java.awt.Font("Verdana", 0, 12));
      jLabel4.setText("Recursive calls/Iterations");

      jLabel3.setFont(new java.awt.Font("Verdana", 0, 12));
      jLabel3.setText("Consistency checks");

      jLabel1.setFont(new java.awt.Font("Verdana", 1, 14));
      jLabel1.setText("Statistics");

      jLabel2.setFont(new java.awt.Font("Verdana", 0, 12));
      jLabel2.setText("Assignments");

      javax.swing.GroupLayout currentRunLayout = new javax.swing.GroupLayout(currentRun);
      currentRun.setLayout(currentRunLayout);
      currentRunLayout.setHorizontalGroup(
         currentRunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, currentRunLayout.createSequentialGroup()
            .addContainerGap(332, Short.MAX_VALUE)
            .addGroup(currentRunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(assignmentsLabel)
               .addComponent(consistencyLabel)
               .addComponent(recursiveLabel)
               .addComponent(elapsedLabel))
            .addGap(30, 30, 30))
         .addGroup(currentRunLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel6)
            .addContainerGap(297, Short.MAX_VALUE))
         .addGroup(currentRunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(currentRunLayout.createSequentialGroup()
               .addContainerGap()
               .addGroup(currentRunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                  .addGroup(javax.swing.GroupLayout.Alignment.LEADING, currentRunLayout.createSequentialGroup()
                     .addGap(10, 10, 10)
                     .addGroup(currentRunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4)
                        .addComponent(jLabel5)))
                  .addGroup(javax.swing.GroupLayout.Alignment.LEADING, currentRunLayout.createSequentialGroup()
                     .addComponent(jLabel1)
                     .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
               .addContainerGap()))
      );
      currentRunLayout.setVerticalGroup(
         currentRunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, currentRunLayout.createSequentialGroup()
            .addContainerGap(44, Short.MAX_VALUE)
            .addComponent(assignmentsLabel)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(consistencyLabel)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(recursiveLabel)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(elapsedLabel)
            .addGap(7, 7, 7)
            .addComponent(jLabel6)
            .addContainerGap())
         .addGroup(currentRunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(currentRunLayout.createSequentialGroup()
               .addContainerGap()
               .addComponent(jLabel1)
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
               .addComponent(jLabel2)
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
               .addComponent(jLabel3)
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
               .addComponent(jLabel4)
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
               .addComponent(jLabel5)
               .addContainerGap(81, Short.MAX_VALUE)))
      );

      jTabbedPane1.addTab("Current run", currentRun);

      javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
      jPanel2.setLayout(jPanel2Layout);
      jPanel2Layout.setHorizontalGroup(
         jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 371, Short.MAX_VALUE)
      );
      jPanel2Layout.setVerticalGroup(
         jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 218, Short.MAX_VALUE)
      );

      jTabbedPane1.addTab("All runs statistics", jPanel2);

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
      this.setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE))
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addGap(12, 12, 12)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(83, Short.MAX_VALUE))
      );

      jTabbedPane1.getAccessibleContext().setAccessibleName("Current run");
   }// </editor-fold>//GEN-END:initComponents


   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JLabel assignmentsLabel;
   private javax.swing.JLabel consistencyLabel;
   private javax.swing.JPanel currentRun;
   private javax.swing.JLabel elapsedLabel;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JLabel jLabel3;
   private javax.swing.JLabel jLabel4;
   private javax.swing.JLabel jLabel5;
   private javax.swing.JLabel jLabel6;
   private javax.swing.JPanel jPanel2;
   private javax.swing.JTabbedPane jTabbedPane1;
   private javax.swing.JLabel recursiveLabel;
   private javax.swing.ImageIcon statisticsImage;
   // End of variables declaration//GEN-END:variables

}
